{
 "title": "Location",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total Trawel Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance_km\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Distance Left for Oil Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance_km\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> sum()\r\n  |> map(fn: (r) => ({ r with _value: 5000.0 - r._value }))\r\n  |> yield(name: \"result\")\r\n"
    }
   ]
  },
  {
   "title": "LAT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lat\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "LON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lon\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Distance for last 1 Hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance_km\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Distance for last 1 Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance_km\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Travel Gap in Last 1 Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance_km\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vel\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Distance for last 7 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance_km\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Distance for last 30 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"location\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance_km\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dainis\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"owntracks\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> sum()\r\n"
    }
   ]
  }
 ]
}